version: '3.7'

secrets:
  db_secrets:
    file: 'secrets/db.secret'
  glacier_secrets:
    file: 'secrets/glacier.secret'
  guardian_db_password:
    external: true
  guardian_db_root_password:
    external: true
  guardian_secrets:
    file: 'secrets/guardian.secret'
  bulwark_gitannex_secrets:
    file: 'secrets/bulwark_gitannex.secret'
  bulwark_rsa:
    external: true

configs:
  known_hosts:
    file: 'known_hosts'
  ssh_config:
    file: 'ssh_config'

services:
  db:
    image: 'mysql:5.7'
    environment:
      MYSQL_DATABASE: guardian_db
      MYSQL_PASSWORD_FILE: /run/secrets/guardian_db_password
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/guardian_db_root_password
      MYSQL_USER: guardian_user
    secrets:
      - guardian_db_password
      - guardian_db_root_password
    volumes:
      - 'db:/var/lib/mysql'
  guardian:
    image: 'guardian:latest'
    depends_on:
      - 'db'
    secrets:
      - db_secrets
      - glacier_secrets
      - guardian_secrets
      - bulwark_gitannex_secrets
      - source: bulwark_rsa
        target: /root/.ssh/bulwark_rsa
        mode: 0600
    configs:
      - source: 'known_hosts'
        target: '/root/.ssh/known_hosts'
      - source: 'ssh_config'
        target: '/root/.ssh/config'
    volumes:
      - 'guardian:/usr/src/app'
      - 'guardian_todos:/todos'
      - '${LOCAL_ZIP_WORKSPACE}:/zip_workspace'
      - '${LOCAL_LOG_FILE}:/usr/src/app/logs'
volumes:
  db:
  guardian:
  guardian_todos:
