version: '3.1'

secrets:
  db_secrets:
    file: 'secrets/db.secret'
  glacier_secrets:
    file: 'secrets/glacier.secret'
  guardian_secrets:
    file: 'secrets/guardian.secret'
  bulwark_gitannex_secrets:
    file: 'secrets/bulwark_gitannex.secret'

services:
  db:
    image: 'guardian_db:5.7'
    secrets:
      - db_secrets
    volumes:
      - 'db:/var/lib/mysql'
  guardian:
    image: 'guardian:latest'
    depends_on:
      - 'db'
    secrets:
      - db_secrets
      - glacier_secrets
      - guardian_secrets
      - bulwark_gitannex_secrets
    volumes:
      - 'guardian:/usr/src/app'
      - 'guardian_todos:/todos'
      - '${LOCAL_BG_REMOTE}:/bulwark_gitannex_remote'
      - '${LOCAL_ZIP_WORKSPACE}:/zip_workspace'
      - '${LOCAL_LOG_FILE}:/usr/src/app/logs'
volumes:
  db:
  guardian:
  guardian_todos:
