version: '3.1'

secrets:
  db_secrets:
    file: 'db.yml'
  stronghold_secrets:
    file: 'stronghold.yml'
  guardian_secrets:
    file: 'guardian.yml'

services:
  db:
    image: 'guardian_db:5.7'
    secrets:
      - db_secrets
    volumes:
      - 'db:/var/lib/mysql'
  guardian:
    image: 'guardian:latest'
    depends_on:
      - 'db'
    secrets:
      - db_secrets
      - stronghold_secrets
      - guardian_secrets
    volumes:
      - 'guardian:/usr/src/app'
      - 'guardian_todos:/todos'

volumes:
  db:
  guardian:
  guardian_todos:
