#!/usr/bin/env ruby

require 'todo_runner'
require 'stronghold'
require 'yaml'

require 'pry'

TodoRunner.define do

  LOG_FILE = 'completion.txt'

  def fetch_source(source, workspace, application, method)

    case application
      when 'bulwark'
        
      when 'openn'
        #TODO: Fill this out
      else
        raise "Invalud application #{application} specified."
    end


  end

  def zip_package(manifest_data)
    fetch_source(manifest_data[:source], manifest_data[:workspace], manifest_data[:application], manifest_data[:method])
    binding.pry
    return true if success
  end

  def glacier_transfer
    return {key: value}, true if success
  end

  def log_complete
    # write a single line to completion file
  end

  def update_fort_db
    # load contents of completion file into fort stronghold db
    File.write(LOG_FILE)
  end

  start :zip

  task :zip, on_fail: :FAIL, next_step: :glacier do |todo_file|
    data = YAML.load todo_file
    zip_package(data)
  end

  task :glacier, on_fail: :FAIL, next_step: :SUCCESS do |todo_file|
    data = YAML.load todo_file
    k_v = glacier_transfer
    log_complete(k_v)
  end

  after :all do
    update_fort_db
  end

end

TodoRunner.run(*ARGV)