#!/usr/bin/env ruby

require 'yaml'

#####
##
## Create a todo file like this:
#
#     ---
#     :source: ljsmisc1.git
#     :zip_dest: dest_dir_for_zips
#     :compressed_source: dest_dir_for_zips/ljsmisc1.zip
#     :glacier_description: "{ json_blob: some_stuff }"
#     :glacier_vault: bulwark
#
#####

def missing_args
  # validate command-line args
end

def create_todo_file(args = {})
  # create individual files
end

# TODO: validate arguments

SmarterCSV.parse(file).each do |row|
  args = get_args(row)
  create_todo_file(args)
end