#!/usr/bin/env ruby

require 'yaml'

#####
##
## Create a todo file like this:
#
#     ---
#     :source: ljsmisc1.git
#     :zip_dest: dest_dir_for_zips
#     :compressed_source: dest_dir_for_zips/ljsmisc1.zip
#     :glacier_description: "{ json_blob: some_stuff }"
#     :glacier_vault: bulwark
#
#####

def validate_args!
  raise ArgumentError.new('Please supply a CSV file') if ARGV[0].nil?
  raise ArgumentError.new("#{ARGV[0]} not found") if File.exist?(ARGV[0]) == false
end

def create_todo_file(args = {})
  # create individual files
end

validate_args!

SmarterCSV.parse(file).each do |row|
  args = get_args(row)
  create_todo_file(args)
end